version: '2'

services:
  myapp:
    image: php:7-apache-stretch
    volumes:
      - ../myapp:/var/www/html
    ports:
      - 80:80
    networks:
      - myapp_network

networks:
  myapp_network:
    external:
      name: myapp_network

